// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sql

import (
	"context"
)

type Querier interface {
	AddToAccountBalanceById(ctx context.Context, arg AddToAccountBalanceByIdParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccountById(ctx context.Context, id int64) (int64, error)
	DeleteEntryById(ctx context.Context, id int64) (int64, error)
	DeleteTransferById(ctx context.Context, id int64) (int64, error)
	GetAccountById(ctx context.Context, id int64) (Account, error)
	GetAccountByIdForUpdate(ctx context.Context, id int64) (Account, error)
	GetAllAccounts(ctx context.Context) ([]Account, error)
	GetAllAccountsPaginated(ctx context.Context, arg GetAllAccountsPaginatedParams) ([]Account, error)
	GetAllEntries(ctx context.Context) ([]Entry, error)
	GetAllEntriesPaginated(ctx context.Context, arg GetAllEntriesPaginatedParams) ([]Entry, error)
	GetAllTransfers(ctx context.Context) ([]Transfer, error)
	GetAllTransfersPaginated(ctx context.Context, arg GetAllTransfersPaginatedParams) ([]Transfer, error)
	GetAllUserAccountsPaginated(ctx context.Context, arg GetAllUserAccountsPaginatedParams) ([]Account, error)
	GetEntryById(ctx context.Context, id int64) (Entry, error)
	GetTransferById(ctx context.Context, id int64) (Transfer, error)
	GetTwoAccountsInvolvedInTransfer(ctx context.Context, arg GetTwoAccountsInvolvedInTransferParams) ([]Account, error)
	GetUserAccountById(ctx context.Context, arg GetUserAccountByIdParams) (Account, error)
	GetUserByUserName(ctx context.Context, username string) (User, error)
	UpdateAccountBalanceById(ctx context.Context, arg UpdateAccountBalanceByIdParams) (Account, error)
	UpdateAccountById(ctx context.Context, arg UpdateAccountByIdParams) (Account, error)
	UpdateEntryById(ctx context.Context, arg UpdateEntryByIdParams) (Entry, error)
	UpdateTransferById(ctx context.Context, arg UpdateTransferByIdParams) (Transfer, error)
}

var _ Querier = (*Queries)(nil)
